[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  'forge-std/=lib/forge-std/src/',
  'solmate/=lib/solmate/src/',
  'scal-std/=lib/scal-std/src/',
  '@openzeppelin/=node_modules/@openzeppelin'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
